# Generated by Django 5.1.6 on 2025-02-25 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDGDus.masterdus')),
            ],
        ),
        migrations.AddField(
            model_name='masterdus',
            name='merek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GDGDus.merek'),
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('stok_awal', models.PositiveIntegerField(default=0)),
                ('stok_masuk', models.PositiveIntegerField(default=0)),
                ('stok_keluar', models.PositiveIntegerField(default=0)),
                ('stok_akhir', models.PositiveIntegerField(default=0)),
                ('tipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDGDus.dus')),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('jumlah_keluar', models.PositiveIntegerField()),
                ('tipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDGDus.dus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('jumlah_masuk', models.PositiveIntegerField()),
                ('tipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDGDus.dus')),
            ],
        ),
    ]
